version: "2"
services:
    db: 
        restart: always
        image: "ladams1776/mongo"
        container_name: "mongodb"
        build: 
            context: ./mongo
            dockerfile: Dockerfile
        volumes:
            - react-timer-db:/var/micro-data/mongodb/data/db
        ports:
            - 27017:27017
        networks:
            react_timer:
                ipv4_address: 172.28.1.4
    
    backend:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "3001:3001"
        image: ladams1776/server
        networks:
            react_timer:
                ipv4_address: 172.28.1.3

    frontend:
        container_name: client
        build: 
            context: ./
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        image: ladams1776/client
        volumes: ["/app"]     # mac
        # volumes: ["/.app"] # windows and linux         
        networks:
            react_timer:
                ipv4_address: 172.28.1.2

networks:
    react_timer:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16                

volumes:
    react-timer-db:
